apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - agent-controller.yaml
  - knowledgebase-controller.yaml
  - organization-controller.yaml
  - organization-admin-clusterrole.yaml
  - repobinding-controller.yaml
  - webhook-configuration.yaml
