// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/bdchatham/ArbiterPipelineInfrastructure/platform/platform-controller/controller/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRepoBindings implements RepoBindingInterface
type FakeRepoBindings struct {
	Fake *FakeV1alpha1
	ns   string
}

var repobindingsResource = v1alpha1.SchemeGroupVersion.WithResource("repobindings")

var repobindingsKind = v1alpha1.SchemeGroupVersion.WithKind("RepoBinding")

// Get takes name of the repoBinding, and returns the corresponding repoBinding object, and an error if there is any.
func (c *FakeRepoBindings) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.RepoBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(repobindingsResource, c.ns, name), &v1alpha1.RepoBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RepoBinding), err
}

// List takes label and field selectors, and returns the list of RepoBindings that match those selectors.
func (c *FakeRepoBindings) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RepoBindingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(repobindingsResource, repobindingsKind, c.ns, opts), &v1alpha1.RepoBindingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RepoBindingList{ListMeta: obj.(*v1alpha1.RepoBindingList).ListMeta}
	for _, item := range obj.(*v1alpha1.RepoBindingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested repoBindings.
func (c *FakeRepoBindings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(repobindingsResource, c.ns, opts))

}

// Create takes the representation of a repoBinding and creates it.  Returns the server's representation of the repoBinding, and an error, if there is any.
func (c *FakeRepoBindings) Create(ctx context.Context, repoBinding *v1alpha1.RepoBinding, opts v1.CreateOptions) (result *v1alpha1.RepoBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(repobindingsResource, c.ns, repoBinding), &v1alpha1.RepoBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RepoBinding), err
}

// Update takes the representation of a repoBinding and updates it. Returns the server's representation of the repoBinding, and an error, if there is any.
func (c *FakeRepoBindings) Update(ctx context.Context, repoBinding *v1alpha1.RepoBinding, opts v1.UpdateOptions) (result *v1alpha1.RepoBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(repobindingsResource, c.ns, repoBinding), &v1alpha1.RepoBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RepoBinding), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRepoBindings) UpdateStatus(ctx context.Context, repoBinding *v1alpha1.RepoBinding, opts v1.UpdateOptions) (*v1alpha1.RepoBinding, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(repobindingsResource, "status", c.ns, repoBinding), &v1alpha1.RepoBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RepoBinding), err
}

// Delete takes name of the repoBinding and deletes it. Returns an error if one occurs.
func (c *FakeRepoBindings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(repobindingsResource, c.ns, name, opts), &v1alpha1.RepoBinding{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRepoBindings) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(repobindingsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.RepoBindingList{})
	return err
}

// Patch applies the patch and returns the patched repoBinding.
func (c *FakeRepoBindings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RepoBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(repobindingsResource, c.ns, name, pt, data, subresources...), &v1alpha1.RepoBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RepoBinding), err
}
