// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	internalversion "github.com/bdchatham/ArbiterPipelineInfrastructure/platform/platform-controller/controller/pkg/client/clientset/versioned/typed/v1alpha1/internalversion"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeV1alpha1 struct {
	*testing.Fake
}

func (c *FakeV1alpha1) Organizations(namespace string) internalversion.OrganizationInterface {
	return &FakeOrganizations{c, namespace}
}

func (c *FakeV1alpha1) RepoBindings(namespace string) internalversion.RepoBindingInterface {
	return &FakeRepoBindings{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
