apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/external-secrets/external-secrets/releases/download/v1.3.1/external-secrets.yaml

namespace: external-secrets

labels:
  - pairs:
      app.kubernetes.io/managed-by: argocd
      app.kubernetes.io/part-of: platform

patches:
  - target:
      kind: Deployment
      name: external-secrets-cert-controller
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args/3
        value: --service-namespace=external-secrets
      - op: replace
        path: /spec/template/spec/containers/0/args/5
        value: --secret-namespace=external-secrets
  - target:
      kind: Deployment
      name: external-secrets-webhook
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args/2
        value: --dns-name=external-secrets-webhook.external-secrets.svc
