apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argo-cd.git
    targetRevision: v3.3.0
    path: manifests
    directory:
      include: "install.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: ""
      kind: ConfigMap
      name: argocd-cm
      jqPathExpressions:
        - .data
        - .metadata.labels
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
