---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventlistener-access
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["eventlisteners", "triggers", "triggerbindings", "triggertemplates", "interceptors", "clusterinterceptors", "clustertriggerbindings"]
    verbs: ["get", "list", "watch"]
