apiVersion: v1
kind: Service
metadata:
  name: dex-nodeport
  namespace: auth-system
spec:
  type: NodePort
  ports:
  - port: 5556
    targetPort: 5556
    nodePort: 30556
    protocol: TCP
  selector:
    app: dex
