apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lighthouse-webhooks
  namespace: pipeline-system
  labels:
    app.kubernetes.io/name: lighthouse
    app.kubernetes.io/component: webhooks
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /hook
        pathType: Prefix
        backend:
          service:
            name: hook
            port:
              number: 80
