apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: pipeline-system
  labels:
    app: lighthouse
    component: config
data:
  config.yaml: |
    # Lighthouse configuration
    
    # Plank configuration (PipelineRun creation)
    plank:
      job_url_template: 'http://tekton-dashboard.pipeline-system/pipelineruns/{{.Namespace}}/{{.PipelineRun}}'
      report_template: 'Job {{.Spec.Job}} {{.Status.State}}. [Details]({{.Status.URL}})'
    
    # Prowjob namespace
    prowjob_namespace: pipeline-system
    
    # Pod namespace  
    pod_namespace: pipeline-system
    
    # Enable in-repo configuration
    # Lighthouse will fetch pipeline configurations from .lighthouse/jenkins-x/ in repositories
    in_repo_config:
      enabled:
        "*": true
      allowed_clusters:
        "*": ["*"]
