apiVersion: v1
kind: ConfigMap
metadata:
  name: plugins
  namespace: pipeline-system
  labels:
    app: lighthouse
    component: config
data:
  plugins.yaml: |
    # Lighthouse plugins configuration
    
    # Enable trigger plugin for all repos
    triggers:
      - repos:
          - bdchatham/ArbiterPipelineInfrastructure
        ignore_ok_to_test: true
