apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: auth-system
  labels:
    app: postgresql
    platform.aphex/component: "authentication"
    platform.aphex/managed-by: "argocd"
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgresql
