// Code generated by client-gen. DO NOT EDIT.

package internalversion

import (
	"context"
	"time"

	v1alpha1 "github.com/bdchatham/ArbiterPipelineInfrastructure/platform/platform-controller/controller/api/v1alpha1"
	scheme "github.com/bdchatham/ArbiterPipelineInfrastructure/platform/platform-controller/controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// RepoBindingsGetter has a method to return a RepoBindingInterface.
// A group's client should implement this interface.
type RepoBindingsGetter interface {
	RepoBindings(namespace string) RepoBindingInterface
}

// RepoBindingInterface has methods to work with RepoBinding resources.
type RepoBindingInterface interface {
	Create(ctx context.Context, repoBinding *v1alpha1.RepoBinding, opts v1.CreateOptions) (*v1alpha1.RepoBinding, error)
	Update(ctx context.Context, repoBinding *v1alpha1.RepoBinding, opts v1.UpdateOptions) (*v1alpha1.RepoBinding, error)
	UpdateStatus(ctx context.Context, repoBinding *v1alpha1.RepoBinding, opts v1.UpdateOptions) (*v1alpha1.RepoBinding, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.RepoBinding, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.RepoBindingList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RepoBinding, err error)
	RepoBindingExpansion
}

// repoBindings implements RepoBindingInterface
type repoBindings struct {
	client rest.Interface
	ns     string
}

// newRepoBindings returns a RepoBindings
func newRepoBindings(c *V1alpha1Client, namespace string) *repoBindings {
	return &repoBindings{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the repoBinding, and returns the corresponding repoBinding object, and an error if there is any.
func (c *repoBindings) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.RepoBinding, err error) {
	result = &v1alpha1.RepoBinding{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("repobindings").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of RepoBindings that match those selectors.
func (c *repoBindings) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RepoBindingList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.RepoBindingList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("repobindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested repoBindings.
func (c *repoBindings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("repobindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a repoBinding and creates it.  Returns the server's representation of the repoBinding, and an error, if there is any.
func (c *repoBindings) Create(ctx context.Context, repoBinding *v1alpha1.RepoBinding, opts v1.CreateOptions) (result *v1alpha1.RepoBinding, err error) {
	result = &v1alpha1.RepoBinding{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("repobindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(repoBinding).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a repoBinding and updates it. Returns the server's representation of the repoBinding, and an error, if there is any.
func (c *repoBindings) Update(ctx context.Context, repoBinding *v1alpha1.RepoBinding, opts v1.UpdateOptions) (result *v1alpha1.RepoBinding, err error) {
	result = &v1alpha1.RepoBinding{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("repobindings").
		Name(repoBinding.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(repoBinding).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *repoBindings) UpdateStatus(ctx context.Context, repoBinding *v1alpha1.RepoBinding, opts v1.UpdateOptions) (result *v1alpha1.RepoBinding, err error) {
	result = &v1alpha1.RepoBinding{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("repobindings").
		Name(repoBinding.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(repoBinding).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the repoBinding and deletes it. Returns an error if one occurs.
func (c *repoBindings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("repobindings").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *repoBindings) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("repobindings").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched repoBinding.
func (c *repoBindings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RepoBinding, err error) {
	result = &v1alpha1.RepoBinding{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("repobindings").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
