apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Tekton Pipelines v0.65.0
  - https://github.com/tektoncd/pipeline/releases/download/v0.65.0/release.yaml
  # Tekton Triggers v0.29.0
  - https://github.com/tektoncd/triggers/releases/download/v0.29.0/release.yaml
  # Tekton Triggers Core Interceptors v0.29.0
  - https://github.com/tektoncd/triggers/releases/download/v0.29.0/interceptors.yaml

# Replace all gcr.io/tekton-releases images with ghcr.io/tektoncd equivalents
images:
  # Tekton Pipelines images
  - name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller
    newName: ghcr.io/tektoncd/github.com/tektoncd/pipeline/cmd/controller
  - name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook
    newName: ghcr.io/tektoncd/github.com/tektoncd/pipeline/cmd/webhook
  - name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/resolvers
    newName: ghcr.io/tektoncd/github.com/tektoncd/pipeline/cmd/resolvers
  - name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/events
    newName: ghcr.io/tektoncd/github.com/tektoncd/pipeline/cmd/events
  - name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint
    newName: ghcr.io/tektoncd/github.com/tektoncd/pipeline/cmd/entrypoint
  - name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop
    newName: ghcr.io/tektoncd/github.com/tektoncd/pipeline/cmd/nop
  - name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/sidecarlogresults
    newName: ghcr.io/tektoncd/github.com/tektoncd/pipeline/cmd/sidecarlogresults
  - name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/workingdirinit
    newName: ghcr.io/tektoncd/github.com/tektoncd/pipeline/cmd/workingdirinit
  
  # Tekton Triggers images
  - name: gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/controller
    newName: ghcr.io/tektoncd/github.com/tektoncd/triggers/cmd/controller
  - name: gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/webhook
    newName: ghcr.io/tektoncd/github.com/tektoncd/triggers/cmd/webhook
  - name: gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/interceptors
    newName: ghcr.io/tektoncd/github.com/tektoncd/triggers/cmd/interceptors
