apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-services

resources:
  # Tekton Pipelines release
  - https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml

images:
  # Patch Tekton images to use ghcr.io registry
  - name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller
    newName: ghcr.io/tektoncd/pipeline/controller
    newTag: v0.56.0
  - name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook
    newName: ghcr.io/tektoncd/pipeline/webhook
    newTag: v0.56.0
  - name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/resolvers
    newName: ghcr.io/tektoncd/pipeline/resolvers
    newTag: v0.56.0
  - name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/events
    newName: ghcr.io/tektoncd/pipeline/events
    newTag: v0.56.0
  - name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint
    newName: ghcr.io/tektoncd/pipeline/entrypoint
    newTag: v0.56.0
  - name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop
    newName: ghcr.io/tektoncd/pipeline/nop
    newTag: v0.56.0
  - name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/sidecarlogresults
    newName: ghcr.io/tektoncd/pipeline/sidecarlogresults
    newTag: v0.56.0
  - name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/workingdirinit
    newName: ghcr.io/tektoncd/pipeline/workingdirinit
    newTag: v0.56.0
