apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-arbiter-dev
  namespace: kube-system
spec:
  secretName: wildcard-arbiter-dev-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.arbiter-dev.com"
    - arbiter-dev.com
