apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: platform-gateway
  namespace: kube-system
spec:
  gatewayClassName: traefik
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.arbiter-dev.com"
      tls:
        mode: Terminate
        certificateRefs:
          - name: wildcard-arbiter-dev-tls
            kind: Secret
      allowedRoutes:
        namespaces:
          from: All
    - name: http
      protocol: HTTP
      port: 80
      hostname: "*.arbiter-dev.com"
      allowedRoutes:
        namespaces:
          from: All
