apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: platform-gateway
  namespace: kong-system
spec:
  gatewayClassName: kong
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.arbiter-dev.com"
      tls:
        mode: Terminate
        certificateRefs:
          - name: wildcard-arbiter-dev-tls
            kind: Secret
      allowedRoutes:
        namespaces:
          from: All
    - name: api
      protocol: HTTPS
      port: 443
      hostname: "aphex.arbiter-dev.com"
      tls:
        mode: Terminate
        certificateRefs:
          - name: wildcard-arbiter-dev-tls
            kind: Secret
      allowedRoutes:
        namespaces:
          from: All
