apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway-api-crds.yaml
  - gateway-class.yaml
  - gateway.yaml
  - routes/argocd.yaml
  - routes/auth.yaml
  - routes/dex.yaml
  - routes/tekton.yaml
  - plugins/rate-limit.yaml
  - plugins/key-auth.yaml
