apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: test-upgrade-tekton
  namespace: pipeline-catalog
spec:
  taskRef:
    name: upgrade-tekton
  params:
    - name: version
      value: "v0.56.0"
