apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
spec:
  postsubmits:
    - name: platform-upgrade
      context: platform-upgrade
      source: "release.yaml"
      branches:
        - ^main$
        - ^mainline$

