apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: test-helm-upgrade
  namespace: pipeline-catalog
spec:
  taskRef:
    name: helm-upgrade
  params:
    - name: chart
      value: "stable/nginx"
    - name: release-name
      value: "test-nginx"
    - name: namespace
      value: "default"
    - name: create-namespace
      value: "false"
  workspaces:
    - name: source
      emptyDir: {}
